# Vehicle Sales Data Audit

## Project Goal

The goal of this project is to analyze the used-vehicle market, identify factors associated with vehicle selling prices, and eventually develop a model for estimating fair market value and identifying potentially underpriced or overpriced vehicles.

This notebook focuses on understanding the raw dataset before making any changes to it.

In [4]:
import pandas as pd

In [15]:
cars = pd.read_csv("../data/raw/car_prices.csv")

In [10]:
import os 

print (os.getcwd())

C:\Users\hamza\Downloads\DS\used-vehicle-market-intelligence\notebooks

In [11]:
os.listdir("../data/raw")

['.gitkeep', 'archive.zip']

In [14]:
os.listdir("../data/raw")

['.gitkeep', 'car_prices.csv']

In [16]:
cars.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [ ]:
## Dataset Overview

The raw dataset contains 558,837 vehicle sale records and 16 variables.

The variables include vehicle year, make, model, trim, body style, transmission, condition, mileage, location, seller, Manheim Market Report (MMR) value, actual selling price, and sale date.

In [17]:
cars.shape

(558837, 16)

In [18]:
cars.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='str')

In [ ]:
## Data Quality Check

Before cleaning the dataset, I inspected:

- column data types
- missing values
- duplicate rows
- numeric distributions
- suspicious or extreme values

No exact duplicate rows were found.

Several variables contain missing values. Transmission has the largest number of missing records, with 65,352 missing values.

In [19]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  str
 2   model         548438 non-null  str
 3   trim          548186 non-null  str
 4   body          545642 non-null  str
 5   transmission  493485 non-null  str
 6   vin           558833 non-null  str
 7   state         558837 non-null  str
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  str
 11  interior      558088 non-null  str
 12  seller        558837 non-null  str
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  str
dtypes: float64(4), int64(1), str(11)
memory usage: 68.2 MB

In [20]:
cars.isna().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [21]:
cars.duplicated().sum()

np.int64(0)

In [22]:
cars.describe()

,year,condition,odometer,mmr,sellingprice
count,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000
mean,2010.038927,30.672365,68320.017767,13769.377495,13611.358810
std,3.966864,13.402832,53398.542821,9679.967174,9749.501628
min,1982.000000,1.000000,1.000000,25.000000,1.000000
25%,2007.000000,23.000000,28371.000000,7100.000000,6900.000000
50%,2012.000000,35.000000,52254.000000,12250.000000,12100.000000
75%,2013.000000,42.000000,99109.000000,18300.000000,18200.000000
max,2015.000000,49.000000,999999.000000,182000.000000,230000.000000

In [23]:
sorted(cars["condition"].dropna().unique())

[np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(4.0),
 np.float64(5.0),
 np.float64(11.0),
 np.float64(12.0),
 np.float64(13.0),
 np.float64(14.0),
 np.float64(15.0),
 np.float64(16.0),
 np.float64(17.0),
 np.float64(18.0),
 np.float64(19.0),
 np.float64(21.0),
 np.float64(22.0),
 np.float64(23.0),
 np.float64(24.0),
 np.float64(25.0),
 np.float64(26.0),
 np.float64(27.0),
 np.float64(28.0),
 np.float64(29.0),
 np.float64(31.0),
 np.float64(32.0),
 np.float64(33.0),
 np.float64(34.0),
 np.float64(35.0),
 np.float64(36.0),
 np.float64(37.0),
 np.float64(38.0),
 np.float64(39.0),
 np.float64(41.0),
 np.float64(42.0),
 np.float64(43.0),
 np.float64(44.0),
 np.float64(45.0),
 np.float64(46.0),
 np.float64(47.0),
 np.float64(48.0),
 np.float64(49.0)]

In [ ]:
## Condition Score Investigation

The `condition` variable uses an unusual numeric encoding.

Examples include:

- 1 = 1.0
- 2 = 2.0
- 5 = 5.0
- 21 = 2.1
- 35 = 3.5
- 49 = 4.9

Whole-number condition grades appear to be stored as single digits, while decimal condition grades are stored without the decimal point.

This column will need to be normalized during data cleaning. The raw values will remain unchanged.

In [24]:
cars["condition"].value_counts().sort_index()

condition
1.0      7364
2.0     20790
3.0     10803
4.0     19922
5.0     11222
11.0       87
12.0       95
13.0       82
14.0      134
15.0      144
16.0      178
17.0      243
18.0      323
19.0    42281
21.0     9199
22.0     6057
23.0     8188
24.0     9326
25.0    12561
26.0    11912
27.0    16351
28.0    19178
29.0    18928
31.0     9222
32.0     9962
33.0    10619
34.0    17398
35.0    26750
36.0    23144
37.0    25938
38.0    18723
39.0    19920
41.0    23073
42.0    24328
43.0    24937
44.0    25514
45.0    12313
46.0    12634
47.0    11363
48.0    12712
49.0    13099
Name: count, dtype: int64

In [25]:
cars[["year", "condition", "odometer", "mmr", "sellingprice"]].describe()

,year,condition,odometer,mmr,sellingprice
count,558837.000000,547017.000000,558743.000000,558799.000000,558825.000000
mean,2010.038927,30.672365,68320.017767,13769.377495,13611.358810
std,3.966864,13.402832,53398.542821,9679.967174,9749.501628
min,1982.000000,1.000000,1.000000,25.000000,1.000000
25%,2007.000000,23.000000,28371.000000,7100.000000,6900.000000
50%,2012.000000,35.000000,52254.000000,12250.000000,12100.000000
75%,2013.000000,42.000000,99109.000000,18300.000000,18200.000000
max,2015.000000,49.000000,999999.000000,182000.000000,230000.000000

In [26]:
cars[cars["sellingprice"] < 500][
    ["year", "make", "model", "condition", "odometer", "mmr", "sellingprice"]
].head(20)

,year,make,model,condition,odometer,mmr,sellingprice
4172,2005,Chrysler,Sebring,NaN,138892.0,1250.0,200.0
4193,2005,Chrysler,PT Cruiser,1.0,1.0,4250.0,300.0
4255,2005,Ford,Freestar,27.0,135139.0,1275.0,450.0
4301,2005,Nissan,Murano,NaN,NaN,4900.0,400.0
4419,2004,Hyundai,Sonata,3.0,130817.0,1675.0,300.0
4453,2004,Chevrolet,Impala,NaN,184157.0,1750.0,300.0
4502,2004,Chrysler,PT Cruiser,2.0,151908.0,1475.0,400.0
4506,2004,dodge,stratus,NaN,160220.0,825.0,250.0
4683,2003,Ford,Focus,1.0,163481.0,1025.0,350.0
4700,2003,Chevrolet,Cavalier,2.0,82420.0,1300.0,400.0
4707,2003,Chevrolet,Impala,2.0,218049.0,675.0,300.0
4708,2003,Ford,Taurus,NaN,191867.0,800.0,300.0
4778,2003,Volkswagen,Jetta,2.0,129516.0,2050.0,300.0
4786,2002,Kia,Sedona,2.0,122662.0,1100.0,400.0
4796,2002,Lincoln,LS,2.0,187444.0,725.0,250.0
4891,2002,Oldsmobile,Intrigue,2.0,200991.0,850.0,400.0
4894,2001,Ford,Expedition,27.0,1.0,1550.0,400.0
4899,2001,Chrysler,Town and Country,2.0,160381.0,850.0,400.0
4908,2001,Ford,Taurus,2.0,128082.0,800.0,300.0
4913,2002,Saturn,S-Series,1.0,145658.0,900.0,300.0

In [27]:
cars[cars["odometer"] > 500000][
    ["year", "make", "model", "condition", "odometer", "mmr", "sellingprice"]
].head(20)

,year,make,model,condition,odometer,mmr,sellingprice
275,2013,Hyundai,Elantra Coupe,1.0,999999.0,8025.0,2500.0
4626,2003,Chevrolet,Silverado 1500,2.0,999999.0,1425.0,700.0
13317,2009,Chevrolet,Cobalt,NaN,999999.0,3375.0,400.0
13480,2009,Dodge,Charger,1.0,999999.0,3850.0,1700.0
13568,2009,Dodge,Charger,1.0,999999.0,4150.0,5500.0
20043,2006,Dodge,Ram Pickup 2500,NaN,500227.0,3175.0,1500.0
20838,2006,Kia,Amanti,1.0,999999.0,900.0,800.0
38465,2012,Nissan,Altima,1.0,999999.0,7375.0,800.0
39178,2009,Dodge,Grand Caravan,1.0,999999.0,3325.0,1500.0
40121,2006,Ford,F-150,19.0,999999.0,7500.0,3600.0
55492,2005,Nissan,Quest,19.0,999999.0,2250.0,2600.0
57588,2008,Nissan,Rogue,1.0,999999.0,3650.0,275.0
58330,2006,chrysler,300,1.0,999999.0,7700.0,2600.0
59320,2004,nissan,350z,1.0,999999.0,4350.0,1100.0
61824,2013,Kia,Optima,1.0,999999.0,17700.0,2700.0
70798,2010,Chevrolet,Cobalt,1.0,999999.0,2850.0,275.0
76882,2008,Chevrolet,Impala,19.0,999999.0,1850.0,1100.0
81661,2012,Hyundai,Sonata,1.0,999999.0,9275.0,800.0
83882,2005,Ford,Escape,19.0,999999.0,850.0,1300.0
84086,2004,Chevrolet,Tahoe,19.0,999999.0,875.0,1800.0

In [28]:
cars["year"].value_counts().sort_index().head(15)

year
1982      2
1983      1
1984      5
1985     10
1986     11
1987      8
1988     11
1989     20
1990     49
1991     67
1992    132
1993    205
1994    392
1995    711
1996    851
Name: count, dtype: int64

In [ ]:
## Extreme Value Investigation

### Odometer

The dataset contains 72 records with an odometer value of exactly 999,999 miles.

Other mileage values above 500,000 occur only once or twice, while 999,999 appears repeatedly. This suggests that 999,999 may represent a special source-system value rather than literal mileage.

The meaning of this value has not been confirmed, so no changes will be made until it is investigated further.

### Selling Price

Several vehicles have recorded selling prices of $1.

Some of these vehicles have MMR values worth thousands or tens of thousands of dollars. These records may represent unusual transactions, data-entry issues, or another special case.

Extremely low prices will be investigated further before they are included in modeling.

In [29]:
cars.nsmallest(20, "sellingprice")[
    ["year", "make", "model", "condition", "odometer", "mmr", "sellingprice"]
]

,year,make,model,condition,odometer,mmr,sellingprice
7566,2002,Ford,F-350 Super Duty,2.0,NaN,7850.0,1.0
48453,2003,Mercedes-Benz,E-Class,21.0,1.0,7325.0,1.0
293223,2014,Ford,E-Series Van,41.0,31886.0,20800.0,1.0
348252,1995,Isuzu,Rodeo,1.0,254132.0,375.0,1.0
5184,1997,ford,explorer,1.0,195748.0,500.0,100.0
25588,2003,Chevrolet,Malibu,1.0,186893.0,950.0,100.0
30275,1993,NaN,NaN,1.0,39750.0,1775.0,100.0
196184,2004,Pontiac,Montana,2.0,106495.0,1700.0,100.0
205309,2002,Chrysler,Sebring,1.0,94937.0,1325.0,100.0
227773,2009,NaN,NaN,2.0,1.0,3825.0,100.0
241038,1997,Mitsubishi,Galant,1.0,226034.0,325.0,100.0
281158,2003,Nissan,Altima,14.0,101792.0,2950.0,100.0
353308,2008,Chrysler,PT Cruiser,25.0,90335.0,3425.0,100.0
384512,2006,Ford,Freestar,18.0,75389.0,2750.0,100.0
406428,2005,Hyundai,Elantra,1.0,999999.0,100.0,100.0
409841,1995,Mercury,Grand Marquis,1.0,165658.0,575.0,100.0
421787,2002,Dodge,Durango,19.0,145161.0,1275.0,100.0
423599,1995,BMW,3 Series,2.0,198766.0,475.0,100.0
443651,2005,Hyundai,Sonata,1.0,255438.0,50.0,100.0
449497,2003,Chevrolet,Impala,19.0,215987.0,550.0,100.0

In [30]:
(cars["odometer"] == 999999).sum()

np.int64(72)

In [31]:
cars[cars["odometer"] > 500000]["odometer"].value_counts().head(20)

odometer
999999.0    72
694978.0     2
500227.0     1
621388.0     1
522212.0     1
537334.0     1
959276.0     1
580956.0     1
980113.0     1
Name: count, dtype: int64

In [4]:
cars["make"].value_counts().head(30)

make
Ford             93554
Chevrolet        60197
Nissan           53946
Toyota           39871
Dodge            30710
Honda            27206
Hyundai          21816
BMW              20719
Kia              18077
Chrysler         17276
Mercedes-Benz    17141
Jeep             15372
Infiniti         15305
Volkswagen       12581
Lexus            11861
GMC              10613
Mazda             8362
Cadillac          7519
Acura             5901
Audi              5869
Lincoln           5757
Buick             5107
Subaru            5043
Ram               4574
Pontiac           4497
Mitsubishi        4140
Volvo             3788
MINI              3224
Saturn            2841
Mercury           1992
Name: count, dtype: int64

In [1]:
import pandas as pd

In [2]:
cars = pd.read_csv("../data/raw/car_prices.csv")

In [3]:
cars.shape

(558837, 16)

In [5]:
cars["transmission"].value_counts(dropna=False)

transmission
automatic    475915
NaN           65352
manual        17544
sedan            15
Sedan            11
Name: count, dtype: int64

In [6]:
cars["body"].value_counts().head(30)

body
Sedan           199437
SUV             119292
sedan            41906
suv              24552
Hatchback        21380
Minivan          21363
Coupe            14602
Wagon            13630
Crew Cab         13280
Convertible       8652
SuperCrew         7423
G Sedan           5999
hatchback         4857
SuperCab          4449
minivan           4166
Regular Cab       4067
Van               3958
Extended Cab      3824
Quad Cab          3436
coupe             3150
crew cab          3114
wagon             2499
convertible       1824
supercrew         1610
E-Series Van      1455
g sedan           1418
G Coupe           1263
Double Cab        1251
supercab           862
regular cab        783
Name: count, dtype: int64

In [7]:
cars["color"].value_counts().head(30)

color
black        110970
white        106673
silver        83389
gray          82857
blue          51139
red           43569
—             24685
green         11382
gold          11342
beige          9222
burgundy       8972
brown          6717
orange         2078
purple         1561
off-white      1449
yellow         1285
charcoal        479
turquoise       236
pink             42
lime             15
4802              1
9410              1
1167              1
2172              1
14872             1
12655             1
15719             1
6388              1
16633             1
11034             1
Name: count, dtype: int64

In [18]:
suspect_transmission = cars["transmission"].isin(["sedan", "Sedan"])
suspect_transmission.sum()

np.int64(26)

In [15]:
numeric_color = cars["color"].astype(str).str.fullmatch(r"\d+")
numeric_color.sum()

np.int64(26)

In [19]:
(suspect_transmission & numeric_color).sum()

np.int64(26)

In [20]:
cars[suspect_transmission & numeric_color][
    ["year", "make", "model", "trim", "body", "transmission",
     "vin", "state", "condition", "odometer", "color",
     "interior", "seller", "mmr", "sellingprice", "saledate"]
].head(30)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
408161,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj4fm201708,NaN,46.0,4802,silver,gray,NaN,13200.0,16500
417835,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj2fm258506,NaN,1.0,9410,white,gray,NaN,13300.0,10500
421289,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj3fm276741,NaN,46.0,1167,blue,black,NaN,13200.0,12700
424161,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj2fm285365,NaN,1.0,2172,gray,black,NaN,14050.0,8250
427040,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj0fm227318,NaN,41.0,14872,gray,black,NaN,13700.0,14300
427043,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj6fm218641,NaN,49.0,12655,red,black,NaN,13850.0,14500
434424,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj7fm223475,NaN,46.0,15719,blue,black,NaN,13650.0,13500
444501,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj5fm297123,NaN,2.0,6388,white,black,NaN,13850.0,10700
453794,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj5fm219943,NaN,44.0,16633,silver,black,NaN,13600.0,13600
461597,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,automatic,3vwd17aj9fm219766,NaN,44.0,11034,black,black,NaN,13900.0,13000
461612,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,Sedan,NaN,3vwd17aj3fm259017,NaN,46.0,2711,white,black,NaN,14250.0,14000
492484,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj5fm206111,NaN,2.0,6864,gray,black,NaN,14000.0,9800
497008,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj5fm273601,NaN,28.0,339,black,black,NaN,14300.0,12900
497011,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj5fm221322,NaN,48.0,18384,silver,black,NaN,13550.0,13500
499083,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj5fm268964,NaN,2.0,9887,red,black,NaN,13900.0,9900
501455,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj6fm231972,NaN,38.0,9837,red,black,NaN,13500.0,12900
505299,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,NaN,3vwd17aj7fm222388,NaN,36.0,20379,silver,black,NaN,13600.0,13500
505306,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj7fm218440,NaN,42.0,20627,white,black,NaN,13600.0,13500
520461,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17ajxfm315938,NaN,1.0,721,blue,gray,NaN,14100.0,8500
528996,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj7fm229552,NaN,38.0,6158,black,black,NaN,13650.0,13400
529009,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,NaN,3vwd17aj8fm298895,NaN,2.0,2817,red,black,NaN,13750.0,12200
529013,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj4fm236636,NaN,5.0,5705,—,black,NaN,13400.0,15250
529622,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj5fm225953,NaN,41.0,18561,black,black,NaN,13200.0,13100
548784,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj7fm326640,NaN,2.0,2846,blue,black,NaN,13600.0,7500
551222,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,NaN,3vwd17aj8fm239622,NaN,2.0,9562,silver,black,NaN,13200.0,12100
554710,2015,Volkswagen,Jetta,SE PZEV w/Connectivity,Navitgation,sedan,automatic,3vwd17aj2fm261566,NaN,48.0,5001,blue,gray,NaN,13400.0,13600

In [1]:
import pandas as pd

In [3]:
cars = pd.read_csv("../data/raw/car_prices.csv")

In [4]:
cars.shape

(558837, 16)

In [5]:
cars["make"].nunique(dropna=True)

96

In [7]:
cars["make"].str.lower().nunique(dropna=True)

66

In [8]:
cars["body"].nunique(dropna=True)

87

In [9]:
cars["body"].str.lower().nunique(dropna=True)

46

In [10]:
cars["model"].nunique(dropna=True)

973

In [11]:
cars["model"].str.lower().nunique(dropna=True)

851

In [14]:
make_variants = (
    cars.dropna(subset=["make"])
    .assign(make_lower = lambda df: df["make"].str.lower())
    .groupby("make_lower")["make"]
    .agg(lambda x: sorted(set(x)))
)

make_variants[make_variants.apply(len)>1].head(30)

make_lower
acura                   [Acura, acura]
audi                      [Audi, audi]
bmw                         [BMW, bmw]
buick                   [Buick, buick]
cadillac          [Cadillac, cadillac]
chevrolet       [Chevrolet, chevrolet]
chrysler          [Chrysler, chrysler]
dodge                   [Dodge, dodge]
ford                      [Ford, ford]
gmc                         [GMC, gmc]
honda                   [Honda, honda]
hyundai             [Hyundai, hyundai]
jeep                      [Jeep, jeep]
kia                         [Kia, kia]
land rover    [Land Rover, land rover]
lexus                   [Lexus, lexus]
lincoln             [Lincoln, lincoln]
maserati          [Maserati, maserati]
mazda                   [Mazda, mazda]
mercury             [Mercury, mercury]
mitsubishi    [Mitsubishi, mitsubishi]
nissan                [Nissan, nissan]
oldsmobile    [Oldsmobile, oldsmobile]
plymouth          [Plymouth, plymouth]
pontiac             [Pontiac, pontiac]
porsche             [Porsche, porsche]
subaru                [Subaru, subaru]
suzuki                [Suzuki, suzuki]
toyota                [Toyota, toyota]
volkswagen    [Volkswagen, volkswagen]
Name: make, dtype: object

In [15]:
body_variants = (
    cars.dropna(subset=["body"])
    .assign(body_lower = lambda df: df["body"].str.lower())
    .groupby("body_lower")["body"]
    .agg(lambda x: sorted(set(x)))
)

body_variants[body_variants.apply(len)>1].head(30)

body_lower
access cab                                          [Access Cab, access cab]
beetle convertible                  [Beetle Convertible, beetle convertible]
cab plus 4                                          [Cab Plus 4, cab plus 4]
club cab                                                [Club Cab, club cab]
convertible                                       [Convertible, convertible]
coupe                                                         [Coupe, coupe]
crew cab                                                [Crew Cab, crew cab]
crewmax cab                                       [CrewMax Cab, crewmax cab]
cts coupe                                             [CTS Coupe, cts coupe]
cts wagon                                             [CTS Wagon, cts wagon]
cts-v coupe                                       [CTS-V Coupe, cts-v coupe]
double cab                                          [Double Cab, double cab]
e-series van                                    [E-Series Van, e-series van]
elantra coupe                                 [Elantra Coupe, elantra coupe]
extended cab                                    [Extended Cab, extended cab]
g convertible                                 [G Convertible, g convertible]
g coupe                                                   [G Coupe, g coupe]
g sedan                                                   [G Sedan, g sedan]
g37 convertible                           [G37 Convertible, g37 convertible]
g37 coupe                                             [G37 Coupe, g37 coupe]
genesis coupe                                 [Genesis Coupe, genesis coupe]
granturismo convertible    [GranTurismo Convertible, granturismo converti...
hatchback                                             [Hatchback, hatchback]
king cab                                                [King Cab, king cab]
koup                                                            [Koup, koup]
mega cab                                                [Mega Cab, mega cab]
minivan                                                   [Minivan, minivan]
promaster cargo van               [Promaster Cargo Van, promaster cargo van]
q60 convertible                           [Q60 Convertible, q60 convertible]
q60 coupe                                             [Q60 Coupe, q60 coupe]
Name: body, dtype: object

In [17]:
text_columns = ["make", "model", "trim", "body", "transmission", "color", "interior"]

for column in text_columns:
    count = (
        cars[column].notna()
        & (cars[column] != cars[column].str.strip())
    ).sum()

    print(column, count)

make 0
model 0
trim 0
body 0
transmission 0
color 0
interior 0